### ISSUE TITLE
problem after downloading the zip file: 

### ISSUE THREAD

**Issue by UGL1** [sublimelsp/LSP-ltex-ls#2]
![image](https://github.com/sublimelsp/LSP-ltex-ls/assets/107758164/84a31b59-31df-4adb-b129-6936ec2bba70)
This is what happens after installing LSP-ltex-ls on Win10, SublimeText Portable latest update, no other teX-related plugins.

**Comment by LDAP** [comment]
I pushed an update that should fix this issue (should land in a few hours on Package Control).

Feel free to reopen if the issue remains.
