### ISSUE TITLE
Adding a word to dictionary causes lsp to restart, which takes a few seconds and consumes a LOT of cpu.

### ISSUE THREAD

**Issue by Roman-Galeev** [sublimelsp/LSP-ltex-ls#4]

**Comment by LDAP** [comment]
This is an issue of https://github.com/sublimelsp/LSP see

- https://github.com/sublimelsp/LSP/issues/2044
- https://github.com/sublimelsp/LSP/issues/2243

I'm afraid, it doesn't seem that this is getting fixed in the near future.

**Comment by Roman-Galeev** [comment]
@LDAP, thanks, looks like a long way indeed. Meanwhile, I believe there might be other workarounds, like keeping it outside of the plugin settings, e.g., in a configurable file location.

What do you think?

**Comment by LDAP** [comment]
I think that is something the server would have to implement. 

By using the configuration, we automatically
- upload the settings on server start
- notify the server if something changes (currently by restart)
- can apply project-wide overrides

If work is put into this, then it would be better to work on the LSP issue instead.

**Comment by Roman-Galeev** [comment]
It seems that there is an option in ltex-lsp for that, which is ignored:
```
        // @see https://valentjn.github.io/vscode-ltex/docs/settings.html#ltexconfigurationtarget
        // vscode-only. Sublime will ignore the settings (for now)
        "ltex.configurationTarget": {
            "dictionary": "user", 
            "disabledRules": "user", 
            "hiddenFalsePositives": "user"
        },
```
Do you recall any context for this "(for now)" comment? And what would be a way to make it not ignored?

**Comment by Roman-Galeev** [comment]
Actually, disregard, it doesn't work anyways, as it needs to be implemented "on the client", which I kind of did following the same logic as ltex itself:
```
configurationTarget.dictionary = ":/path/to/file"
dictionary = { "en-US": [ ":/path/to/file" ] }
```

and then in the plugin itself it injects it in `on_workspace_configuration`, and on `_ltex.addToDictionary` I trigger configuration reload with: `session.send_notification(Notification("workspace/didChangeConfiguration"))`

**Comment by LDAP** [comment]
Yeah, that was the reason for the "for now" if I recall correctly.
